#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

GRADLE_CACHE_DIR=$DIB_IMAGE_CACHE/gradle
mkdir -p $GRADLE_CACHE_DIR

sudo mkdir -p $TMP_MOUNT_PATH/tmp/gradle-cache
sudo mount --bind $GRADLE_CACHE_DIR $TMP_MOUNT_PATH/tmp/gradle-cache
